name: Base Workflow
on:
  pull_request:
    branches:
      - test

jobs:
  whoami:
    name: I'm base
    runs-on: ubuntu-latest
    steps:
      - name: Base Info
        run: |
          echo "I'm base"
          echo "branch = ${{ github.event.pull_request.head.ref }}"
