name: Child

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - name: whoami
        run: |
          "echo 'Im child'"
