name: Workflow Run

on:
  workflow_run:
    workflows: ["Child"]
    types:
      - completed
    branches: ["dev"]

jobs:
  whoami:
    runs-on: ubuntu-latest
    env:
      SOME_EVENT: ${{ github.event.workflow_run }}
    steps:
      - name: whoami
        run: |
          echo "Im workflow run"; echo "$SOME_EVENT"
