name: secret-leak
run-name: Github Actions log secret leak
on: 
  create:
      types: issue
jobs:
  leak-secret:
    runs-on: ubuntu
    steps:
    - shell: bash
      env:
        MY_FIRST_SECRET: ${{ secrets.MY_FIRST_SECRET }}
      run: |
        echo "$MY_FIRST_SECRET"
