name: secret-leak
run-name: Github Actions log secret leak
on: push
jobs:
  leak-secret:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        MY_FIRST_SECRET: ${{ secrets.MY_FIRST_SECRET }}
      run: |
        echo "$MY_FIRST_SECRET"
    - shell: bash
      env:
        MY_JSON_SECRET: ${{ secrets.MY_JSON_SECRET }}
      run: |
        echo "$MY_JSON_SECRET"
    - name: Leak secret via action
      id: action_leak
      uses: ./.github/actions/action-leak-secret@v1.1
      with:
        data: ${{ secrets.MY_JSON_SECRET }}
    - name: Leak dummy google via action
      id: dummy_google_leak
      uses: ./.github/actions/action-leak-secret@v1.1
      with:
        data: ${{ secrets.DUMMY_GOOGLE_SECRET }}
