name: secret-leak
run-name: Github Actions log secret leak
on: 
  issues:
      types: [opened, edited, reopened]
jobs:
  leak-secret:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        MY_FIRST_SECRET: ${{ secrets.MY_FIRST_SECRET }}
      run: |
        echo "$MY_FIRST_SECRET"
